### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by theAdhocracy** [ethercreative/sidebar-entrytypes#3]
Are there any plans to upgrade this plugin to Craft 4? There are a few new features that I would like access to, but currently entry types in the sidebar are a much bigger need, so holding off on the upgrade until this is available.

**Comment by justinholtweb** [comment]
+1 on this request.

**Comment by alexjcollins** [comment]
Hey, we're definitely planning on making the update.
We'll have a chat internally, and I'll come back with an idea of timescales.

**Comment by theAdhocracy** [comment]
Any further updates on this?

**Comment by alexjcollins** [comment]
Ryan kindly created a pull request which we'll be merging soon.
https://github.com/ethercreative/sidebar-entrytypes/pull/4

**Comment by jamesedmonston** [comment]
I've just merged and release @ryanirelan's PR!
