### ISSUE TITLE
Empty entry types after upgrade to Craft v4

### ISSUE THREAD

**Issue by Dathix** [ethercreative/sidebar-entrytypes#6]
Thanks in advance for the amazing work but currently we are having some issues with the plugin. After we upgraded to Craft v4 and renewed the license the entry types remained empty. We can still see all entry types on the parent channel page. The button for adding a new entry also has no effect anymore, it just opens a dropdown to select the type for the new entry. Under Craft v3 the plugin worked flawlessly. I already reactivated the plugin with no luck. Do you guys have any idea?

**Comment by alexjcollins** [comment]
Hey @Dathix, thanks for reporting.
I can replicate the issue, so we'll get this looked into and resolved.

**Comment by Dathix** [comment]
@jamesedmonston Thank you for the quick fix, all issues are resolved!
